name: gemini3_pro_app
description: Gemini 3 Pro 图像生成器安卓APP

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # 状态管理
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # 网络请求
  dio: ^5.4.0
  
  # 图片处理
  image_picker: ^1.0.7
  photo_view: ^0.14.0
  cached_network_image: ^3.3.1
  image: ^4.1.3
  
  # 本地存储
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  
  # UI组件
  flutter_staggered_grid_view: ^0.7.0
  expandable: ^5.0.1
  flutter_slidable: ^3.0.1
  
  # 权限管理
  permission_handler: ^11.2.0
  
  # 工具
  intl: ^0.19.0
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  
  # 平台适配
  device_info_plus: ^9.1.2
  flutter_screenutil: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  freezed: ^2.4.6

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: NotoSansSC
      fonts:
        - asset: assets/fonts/NotoSansSC-Regular.otf
        - asset: assets/fonts/NotoSansSC-Bold.otf
          weight: 700
        - asset: assets/fonts/NotoSansSC-Medium.otf
          weight: 500
